### PR TITLE
FIREFLY-1185:Update server links and imports

### PR DESCRIPTION
**Pull request by joycek-ipac**
Firefly-1185: Update server links and imports
- Edit URL for server to be IRSA Viewer and include Slate in all example notebooks
- Remove old imports for Python 2/3 compatibility

### CODE REVIEW

**Comment by jaladh-singhal** [comment]
@joycek-ipac thanks for the python compatibility changes and adding missing explanation.

I'm trying to understand the reasoning behind following changes in all notebooks:
- changing server url to irsaviewer - is it because not everyone has firefly server locally hosted?
- setting html_path to slate.html - it's optional argument (if `ENV_FF_HTML` environment variable isn't set, it will default to `slate.html`), are we using these notebooks where we need to override this environment variable?
- setting channel param to a string, it's not really required if you use `FireflyClient.make_client(url)` - this way channel will be auto-generated as a unique string.

I think we need to update readme as well as documentation to use `FireflyClient.make_client(url)` classmethod rather than `FireflyClient(url, channel)` constructor for creating `fc` object (created a PR for that, see #52).

**Comment by jaladh-singhal** [comment]
From slack, @joycek-ipac:
> Hi, Jaladh! It’s been a while since I last looked at the pull request, so I’ll try and answer as much as I can.
> 
> 1. Yes, the main idea behind changing the server URL to IRSA Viewer (as seen in basic-demo example) was so that people could use a Firefly server easily without having to check if one has a local server. Also from what I know, the link used in several other examples (http://127.0.0.1:8080/firefly) hasn’t worked for a while.
> 2. Setting html_path to slate.html was explicitly needed for functions involving cells to work (ex. add_cell) when I worked on the notebooks. Maybe it was updated and I wasn’t aware of that, but I’ve [recently] tried add_cell on a browser with IRSA Viewer and it didn’t appear to work , so I kept that argument in.
> 3. There was an initializing error that I kept coming across when I didn’t have that string for channel parameters:
> TypeError: __init__() missing 1 required positional argument: 'channel'
> At the time I meant to change as little as possible regarding methods, but if FireflyClient.make_client(url) is preferred for all examples then perhaps I could change it in all cases.
> 
> If the readme and documentation is updated as per your separate pull request (https://github.com/Caltech-IPAC/firefly_client/pull/52), that would be very helpful!


1. Ok makes sense to use irsaviewer aka public server. Although 'http://127.0.0.1:8080/firefly' is working for me. So we can just put it in comments if anyone wants to switch.
2. I just tested add_cell method without setting html_path and with irsaviewer, it's defaulting to slate.html as it should. Maybe that didn't work because you intitalised firefly_client differently.
3. Ok - we can change it then.

How about I push these changes to this branch, and then you can test if each notebook is working fine @joycek-ipac?

**Comment by joycek-ipac** [comment]
Yes, I can test the files on the updated branch and see if they work when I try running each notebook.
Perhaps IRSA Viewer initialized with slate.html as default using the changes you push will have methods function correctly in that case.

**Comment by jaladh-singhal** [comment]
@joycek-ipac I pushed a commit to address my comments above. Please checkout this branch and test these notebooks again and let me know.

**Comment by jaladh-singhal** [comment]
@robyww @joycek-ipac take a look at https://app.reviewnb.com/Caltech-IPAC/firefly_client/pull/50/ for rendered diff of all notebooks (instead of JSON diff that github shows)

(Note: it will ask you to authenticate using github if you have never used reviewnb before, it's just one time thing)

**Review by robyww — APPROVED** [review]
The changes all look good to me. @jaladh-singhal thanks for setting up the notebook diff tool.

**Comment by jaladh-singhal** [comment]
@joycek-ipac I see your comment on another pull request. Just double checking, you tested it and it's ready for merge, right?

**Comment by joycek-ipac** [comment]
Yes, I think this specific request should be ready for merging.

**Pull request merged**
